#version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-finanzas
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped
    
